version: 2

project_name: apptide

builds:
  - main: .
    id: apptide
    binary: apptide
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X github.com/lucasassuncao/apptide/cmd.Version={{.Version}}"

archives:
  - formats: [binary]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files: []

release:
  github:
    owner: lucasassuncao
    name: apptide
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
